### ISSUE TITLE
Permutational distribution of IP-StudentFisher test statistic

### ISSUE THREAD

**Issue by danielemule** [ilovato/nevada#8]
The permutational distribution of IP-StudentFisher test statistic, the default one proposed by the function `test2_global`, seems to have suspicious behavior. In particular, it presents a **long tail on the left under the null hypothesis**. By definition, large values of IP-StudentFisher statistic should be related to the alternative hypothesis.

You can give a look to this issue replicating the following code:
```
set.seed(301097)
mod=c("k_regular","gnp","smallworld","pa")
n=20
ip_stat=c("flipr:student_ip", "flipr:fisher_ip")
pvalues=matrix(-1,nrow=4,ncol=4)

par(mfrow=c(4,4))
for (i in 1:4) {
  for (j in 1:4) {
    x <- nvd(model = mod[i], n = n, lambda = 5, size = 20, prob = 0.25)
    y <- nvd(model = mod[j], n = n, lambda = 5, size = 20, prob = 0.25)
    
    t2 <- test2_global(x,  y,  seed = 1234, stats = ip_stat)
    pvalues[i,j]=t2$pvalue
    
    T_stat = t2$null_distribution
    T0 = t2$observed
    hist(T_stat,xlim=range(c(T_stat,T0)),breaks=30)
    abline(v=T0,col=3,lwd=2)
  }
}
pvalues
```

It shows the histograms of the permutational distribution of IP-StudentFisher test statistic, related to the pairwise comparison of samples generated from different models.

**Comment by danielemule** [comment]
There was no time last times, but I think that it is reasonable since the IP-StudentFisher statistic is created via NPC using Tippett's combining function (in favor of large values).

**Comment by astamm** [comment]
Should we close this issue or keep it open for further investigation then?

**Comment by danielemule** [comment]
I think we can close this issue, since my own tries on tests based on this statistic have given expected results.
